services:
  db:
    image: postgres:16
    container_name: patient_service_postgres
    environment:
      POSTGRES_DB: patient_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - patient_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d patient_service_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  patient-service:
    image: patient-service
    build: ./patient-service
    container_name: patient_service_app
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/patient_service_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001

  billing-service:
    image: billing-service
    build: ./billing-service
    container_name: billing_service_app
    ports:
      - "4001:4001"
      - "9001:9001"
    depends_on:
      patient-service:
        condition: service_started




volumes:
  patient_pgdata:


